apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
  ref:
    tag: 0.95.0
    digest: sha256:c18a44589ebb3f8be9e1497a09392e2c6091d31d28a9a1cd2f9e9b1158f0ce5c
