apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
  ref:
    tag: 0.95.0
