apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: vaultwarden
