apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-nfs
  namespace: csi-nfs
spec:
  values:
    controller:
      enableSnapshotter: false
    storageClass:
      create: true
      name: nfs-csi
      parameters:
        server: 192.168.100.3
        share: /data
        mountPermissions: "0755"
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      mountOptions:
        - nfsvers=4.1
