apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-vars
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  cluster_name: prod-k3s-proxmox
  cluster_subdomain: apps.sleepfox.ru
  cluster_lb_ip: 192.168.100.24
  storage_class: topolvm-provisioner
