apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/immich
  - http-route.yaml
patches:
  - path: pvc.yaml
  - path: cnpg-cluster.yaml
  - path: oci-repository.yaml
  - path: helm-release.yaml
