apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: immich
spec:
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.13.4
    digest: sha256:9957cfe69ed64f4d4550f39b369c6cf3b2b040bb4d9a5abdced9a60c1153093f
