apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: immich
spec:
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.13.3
    digest: sha256:4b4b2c028a7d7ea0016bd9817b2542638ba035bca96c63643ee9a4118e99af62
