apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  values:
    defaultPodOptions:
      labels:
        app.kubernetes.io/part-of: media
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: media
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/prowlarr
              # renovate: datasource=docker depName=lscr.io/linuxserver/prowlarr
              tag: 2.6.5.5623-ls162
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Etc/UTC
            ports:
              - name: http
                containerPort: 9696
                protocol: TCP
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi
    service:
      main:
        controller: main
        forceRename: prowlarr
        type: ClusterIP
        ports:
          http:
            port: 9696
    persistence:
      config:
        type: persistentVolumeClaim
        forceRename: prowlarr-config
        accessMode: ReadWriteOnce
        storageClass: ${storage_class}
        size: 500Mi
        globalMounts:
          - path: /config
