apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:HjOfRArfOYOEiNxcrhtC+35xtMM4YeKvXBU9VVEtexXA/HKi80vBIA==,iv:lk8/puypZNF5bUuAWN2w58h46hEyhYhSkKWjqw7BJ9s=,tag:BJUcSsDx2bo4WFYviA4KgQ==,type:str]
sops:
    age:
        - recipient: age1w80auv3csedkn7dnx0dhkf09xuhgaughwngsrcs5w65u9m2m5qlqwck6f2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZmlwaXZ1NFk2QmZVRFFI
            VE1qZWRjdEYvOCtDSDczTnlDNkRMUzBwZmlBCkowTVVHdkJkRmZGRHhRakFURVl2
            N29MV0FWd212TDlWbXJQcHVTc0ZPOHcKLS0tIFNacEFkZnowTGJ4aTR6SXNLbW8w
            dU1ZajMxeWtHaERMUEprSXhUaStlTVkKpDUk2ZFRT2T2AZSCnIoI7LBfGR2Nlvg2
            QkbEAJGVTiM6uQ7Www/o9aG+PoTFuH6aLqku46fzZ3jWX/yqTcjjYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T06:53:08Z"
    mac: ENC[AES256_GCM,data:F6FvXA98lxTVRb1YfOdK1TGXcAl+YUJxUdKhPn6uh4DvtDuMJQGUDLK8kbIriUJJJYDNy1nvCNoi52DqgDXhj23qUX3LOaom2y9l8v6lxELi4jyyNf6cOT09k3QIUDJLafe/u4f8nt5vWwLAAX0gGGPEuSxCAp4NC5HqBpDPRvw=,iv:3RyzRa8xFDMyxHadDMZOI+nEX7UdEJhIy/DpRHB005c=,tag:c1nwECjvQZ9TWznjHxTI+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
