apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  values:
    defaultPodOptions:
      labels:
        app.kubernetes.io/part-of: media
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: media
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/jellyfin
              # renovate: datasource=docker depName=lscr.io/linuxserver/jellyfin
              tag: 12.1ubu2604-ls51
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Etc/UTC
            ports:
              - name: http
                containerPort: 8096
                protocol: TCP
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                memory: 1Gi
    service:
      main:
        controller: main
        forceRename: jellyfin
        type: ClusterIP
        ports:
          http:
            port: 8096
    persistence:
      config:
        type: persistentVolumeClaim
        forceRename: jellyfin-config
        accessMode: ReadWriteOnce
        storageClass: ${storage_class}
        size: 3Gi
        globalMounts:
          - path: /config
      media:
        type: persistentVolumeClaim
        existingClaim: media-data-pvc
        globalMounts:
          - path: /data/media
            readOnly: true
