apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium-system
spec:
  interval: 15m
  timeout: 2m
  chartRef:
    kind: OCIRepository
    name: cilium
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    crds:
      enabled: true
