apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 24h
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: v1.9.1
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
