apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - media-pvc.yaml
  - downloads-pvc.yaml
  - helm-repo-bjw-s.yaml
  - jellyfin.yaml
  - sonarr.yaml
  - radarr.yaml
  - qbittorrent.yaml
  - seerr.yaml
