apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  values:
    defaultPodOptions:
      labels:
        app.kubernetes.io/part-of: media
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: media
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/qbittorrent
              # renovate: datasource=docker depName=lscr.io/linuxserver/qbittorrent
              tag: 5.2.4_v2.0.15-ls479@sha256:b522f9f4b769f8f36d49d22d5eb6a92e9aa18904c6a1830b1439df511ec21983
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: Etc/UTC
              WEBUI_PORT: "8080"
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      main:
        controller: main
        forceRename: qbittorrent
        type: ClusterIP
        ports:
          http:
            port: 8080
    persistence:
      config:
        type: persistentVolumeClaim
        forceRename: qbittorrent-config
        accessMode: ReadWriteOnce
        storageClass: ${storage_class}
        size: 500Mi
        globalMounts:
          - path: /config
      data:
        type: persistentVolumeClaim
        existingClaim: media-data-pvc
        globalMounts:
          - path: /data
