apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: topolvm
  namespace: topolvm-system
spec:
  interval: 15m
  timeout: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  chart:
    spec:
      chart: topolvm
      sourceRef:
        kind: HelmRepository
        name: topolvm
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    lvmd:
      deviceClasses:
        - name: ssd
          volume-group: topolvm
          default: true
          spare-gb: 5
