apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  timeout: 15m
  releaseName: immich
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  chartRef:
    kind: OCIRepository
    name: immich
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              # renovate: datasource=docker depName=ghcr.io/immich-app/immich-server versioning=semver
              tag: v3.1.0
            env:
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: uri
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
    valkey:
      enabled: true
