apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  timeout: 15m
  releaseName: immich
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  chartRef:
    kind: OCIRepository
    name: immich
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              # renovate: datasource=docker depName=ghcr.io/immich-app/immich-server versioning=semver
              tag: v3.1.0
            env:
              REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: uri
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
    machine-learning:
      persistence:
        tmp:
          type: emptyDir
    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
      persistence:
        data:
          enabled: true
          size: 1Gi
          type: emptyDir
          accessMode: ReadWriteOnce
