apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  timeout: 15m
  releaseName: immich
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
  chartRef:
    kind: OCIRepository
    name: immich
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: v3.1.0
            env:
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: host
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: user
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: password
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-database-app
                    key: dbname
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
    valkey:
      enabled: true
      persistence:
        data:
          enabled: true
          type: persistentVolumeClaim
          size: 1Gi
          accessMode: ReadWriteOnce
          storageClass: local-path
    server:
      route:
        main:
          enabled: true
          kind: HTTPRoute
          parentRefs:
            - name: internal
              namespace: envoy-gateway-system
              sectionName: https
          hostnames:
            - immich.${cluster_subdomain}
    machine-learning:
      persistence:
        cache:
          enabled: true
          type: persistentVolumeClaim
          size: 5Gi
          accessMode: ReadWriteOnce
          storageClass: local-path
