apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  chart:
    spec:
      version: "5.2.1"
  values:
    controllers:
      main:
        containers:
          main:
            image:
              tag: latest
    persistence:
      config:
        storageClass: ${storage_class}
