apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  interval: 24h
  url: oci://ghcr.io/helmforgedev/helm/adguard-home
  ref:
    tag: 1.5.2
