apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  url: oci://docker.io/envoyproxy/gateway-helm
  ref:
    tag: v1.9.1
