apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
  namespace: cnpg-system
spec:
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    tag: 0.29.1
    digest: sha256:3245fa051bb21d0dd9246272f57a2760b4234817a164a3167d2a1e7fb9f63fd9
