apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmks
  namespace: monitoring
spec:
  interval: 15m
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    defaultRules:
      create: false
    alertmanager:
      enabled: false
    vmalert:
      enabled: false
