apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-nfs
  namespace: csi-nfs
spec:
  interval: 15m
  timeout: 5m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: csi-driver-nfs
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: csi-nfs
